# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  test:
    jobs:
      - mytest

jobs:
  mytest:
    docker:
      - image: continuumio/miniconda3

    steps:
      - checkout

      - run:
          name: Setup Anacoda
          command: |
            which python
            python --version
            which conda
            conda update --all
            conda init bash
            ls
            conda install --file environment.yml
            ./run_tests.sh
